SELECT DATE(Transaction_DATETIME) As Date, MAX(AMOUNT) As Max_Amount
FROM IXF_TRANSACTION
WHERE TRANSATION_TYPE_FK LIKE "1235"
GROUP BY ACCOUNT_NUMBER, DATE(Transaction_DATETIME)
ORDER BY ACCOUNT_NUMBER;